version: 2.0.{build}
image:
  - Visual Studio 2017
environment:
  matrix:
    - solution_name: win32/sdlpal.sln
      APPX_OPTIONS:
    - solution_name: winrt/SDLPal.UWP.sln
      APPX_OPTIONS:  /p:AppxBundle=Always;AppxBundlePlatforms="x86|x64|ARM";AppxPackageDir="AppPackages"
build_script:
  - |-
    if "%APPVEYOR_REPO_TAG%" == "false" ( set APPX_OPTIONS= )
    msbuild /nologo /m %solution_name% /p:Configuration=Release %APPX_OPTIONS%
before_build:
  - |-
    git submodule update --init --recursive
after_build:
  - |-
    if exist win32\Win32\Release\sdlpal.exe ( cd win32\Win32\Release & 7z a ..\..\..\sdlpal-win32.zip sdlpal.exe & cd ..\..\..\ )
    for /d %%d in ("winrt\SDLPal.UWP\AppPackages\*") do ( cd %%d & del /q *.appxsym & 7z a ..\..\..\..\sdlpal-uwp.zip * & cd ..\..\..\..\ )

deploy:
- provider: GitHub
  on:
    appveyor_repo_tag: true
  auth_token:
    secure: RYDRqm5LncsJG32FRSlCkLzkJC4ykCtlgO3+xW4q80wQOA3U9pHAe2beyMEduJIe

artifacts:
  - path: sdlpal-win32.zip
    name: Win32
  - path: sdlpal-uwp.zip
    name: UWP

notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/2accb0e6e37119e604b3
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
